version: '3'

services:

  zk-watch2kafka:
    build:
      context: './'
    command: config.json
    container_name: zk-watch2kafka
    environment:
      JAVA_OPTIONS: '-Xmx128m'
      LOG_LEVEL: DEBUG
    links:
      - kafka
      - zookeeper
    volumes:
      - './dev/dev-config.json:/app/config.json'

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: kafka
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    environment:
      ZOO_STANDALONE_ENABLED: 'true'
    hostname: zookeeper
    restart: always
