version: '3'

services:

  zk-watch2kafka:
    build:
      context: './'
    container_name: zk-watch2kafka
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    environment:
      ZOO_STANDALONE_ENABLED: 'true'
    hostname: zookeeper
    restart: always
